apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatgpt-tg-bot.fullname" . }}-config
  labels:
    {{- include "chatgpt-tg-bot.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ tpl (.Files.Get "files/config.yml") . | indent 6 }}
